CREATE TABLE T (c1 INT, c2 INT);
INSERT INTO T (c1, c2) VALUES (1, 2);
INSERT INTO T (c1, c2) VALUES (2, 4);
INSERT INTO T (c1, c2) VALUES (3, 6);

SELECT COUNT(*) FROM T;
SELECT c1, c2 FROM T WHERE c1 IN (SELECT c1 FROM T WHERE c2 < 3);

DROP TABLE T;
